// <auto-generated />
namespace Finance.Repository.Ef.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CounterStore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CounterStore));
        
        string IMigrationMetadata.Id
        {
            get { return "201609070747044_CounterStore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
