// <auto-generated />
namespace Finance.Repository.EfCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FinanceCompanyAccountManager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinanceCompanyAccountManager));
        
        string IMigrationMetadata.Id
        {
            get { return "201702061941201_FinanceCompanyAccountManager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
